### ISSUE TITLE
updating selectedIndex by passing new prop value whilst mounted

### ISSUE THREAD

**Issue by soumasandesu** [JamesBliss/react-flickity#1]
Is it possible and suitable to make it able for a parent Component to pass new selectedIndex through e.g. FlickityComponent.props.selectedIndex?
I have a private project which needs to update the Flickity's selectedIndex from parent.
I (probably) know where to change the code and may submit a PR for you if necessary.

**Comment by JamesBliss** [comment]
Hi @hkgsherlock 

We could add in a prop for moving index or at the moment you have access to the whole flickity object.

Add a onBuild callback:
```
 <Flickity onBuild={ (flickity) => this.onBuild(flickity) }} >
```

Then use that callback to set flickity in state:
```
  onBuild = (flickity) => {
    this.setState(() => {
      return { flickity };
    });
  }
```

Add then run a function on change to update the function:
```
selectCell = () => {
  const { flickity } = this.state.
  flickity.select(insert new index);
}
```

Or would you prefer me to add a simple prop?

**Comment by soumasandesu** [comment]
Yes I was thinking about passing from prop.
Since every time the `number`-typed prop updated will cause `componentWillReceiveProps(...)` to be fired, there's place for the component in its lifecycle to call `(i) => this.flkty.select(i)` in order to update selected item index inside Flickity. 
IMO this approach should be more comply with the lifecycle of React Components?

Another concern I was thinking about, is that I would then be having too much access to the Flickity object, and (might) cause your component malfunction. 😆 
Though your approach can reduce your workload and let others to mod as how they want it to be.

**Comment by JamesBliss** [comment]
It's important to expose the whole object as you said those who want to do a lot of changes, for example if you want to create your own navigation you need access to the whole flickity object.

In regards to the passing of the selectedIndex the way flickity works is kind of anti-react to begin with but we can try and make it a little more 'reacty'. I agree that maybe a simple fire and forget way to move slide would be good. Maybe make it so you can pass 'previous', 'next' or a number?

**Comment by soumasandesu** [comment]
`number`.
Here's my scenario: In the parent component, it includes your `react-flickity` and a Calendar-like components. The user may select a date through either one of these components. Which means, when the user selected a new date from calendar, the Flickity should *jump* to the index of that date.

**Comment by JamesBliss** [comment]
So do you have a something like `this.state.calendarIndex` which you want to use for both?

**Comment by soumasandesu** [comment]
I think I'll just give a PR to you instead.

**Comment by soumasandesu** [comment]
I spend a week thinking about which of these two options are the best for general purpose, and turns out that your option is still kinda better 😆 I'll submit a PR to you later today.

The Flickity object will be exposed like how `React.Component[ref]` works, so it'd be easier for other devs to understand.
